name: boyo3_v1
description: "A new Flutter project."

publish_to: 'none'
version: 1.4.0+5

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:


  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  http: ^1.1.0
  flutter_carousel_widget: ^2.2.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.7.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  device_preview: ^1.1.0

  iconly: ^1.0.1
  image_picker: ^1.0.7
  intl: any
  json_annotation: ^4.8.1
  location: ^5.0.3
  lottie: ^3.1.0
  pinput: ^4.0.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  share_plus: ^9.0.0
  equatable: ^2.0.5
  video_player: ^2.9.2

dev_dependencies:
  build_runner: ^2.4.8

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/bio3Icon.png"
  min_sdk_android: 21
flutter:
  generate: true

  uses-material-design: true
  fonts:
    - family: Jannah
      fonts:
        - asset: assets/fonts/jannah.ttf
          weight: 700
    - family: Tajawal
      fonts:
        - asset: assets/fonts/TajawalBold.ttf
          weight: 700
  assets:
    - assets/videos/intro.mp4
    - assets/images/
    - assets/images/splash.json
    - assets/images/boyo3_splash.json
    - assets/images/boyo3_lottie.json
    - assets/images/png_icons/home.png
    - assets/images/png_icons/4x4.png
    - assets/images/png_icons/caravan.png
    - assets/images/png_icons/motorcycle.png
    - assets/images/png_icons/motorcycle.png
    - assets/images/png_icons/tools.png
    - assets/images/png_icons/service.png
    - assets/images/png_icons/workshop.png
    - assets/images/png_icons/shop.png
    - assets/images/png_icons/packages.png
    - assets/images/png_icons/auction.png
    - assets/images/png_icons/camping.png
    - assets/images/png_icons/generator.png
